#!/bin/sh
echo "Creating roles..."
psql -o /dev/null <<EOF
CREATE ROLE "${PG_ADMIN_USER}" ENCRYPTED PASSWORD '${PG_ADMIN_PASS}' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE ROLE "${PG_CLIENT_USER}" ENCRYPTED PASSWORD '${PG_CLIENT_PASS}' INHERIT LOGIN;
EOF
